title:
  de: Seite
  en: Page

icon: 📃

tabs:
  dashboard:
    label:
      de: Inhalt
      en: Content
    icon: draft
    columns:
      - width: 2/3
        sections:
          main: sections/blocks

      - width: 1/3
        sections:
          meta: sections/meta
          helpers: sections/punctuation

  images: tabs/images
  files: tabs/files
