title:
  de: Seite
  en: Page

icon: 📃

tabs:
  page:
    label:
      de: Inhalt
      en: Content
    icon: draft
    columns:
      - width: 2/3
        sections:
          info:
            type: fields
            fields:
              customTitle:
                extends: fields/customTitle
                width: 1/2
              cover:
                extends: fields/thumbnail
                width: 1/2

      - width: 1/3
        sections:
          meta:
            type: fields
            fields:
              description: fields/description

      - width: 2/3
        sections:
          blocks: sections/blocks

      - width: 1/3
        sticky: true
        sections:
          punctuation: sections/punctuation

  images: tabs/images
  files: tabs/files
